### ISSUE TITLE
Make expert harder

### ISSUE THREAD

**Issue by rilifon** [MarvellousSoft/liquidum#140]
Been playing a bunch of explorer mode to playtest difficulties. Easy through hard seem good, expert seems pretty much the same difficulty as hard, but sometimes with a few different but not as relevant rules to solve. Is there a pratical way to make it slightly harder without being "interesting"? Maybe bigger or try to reduce amount of hints?

**Comment by yancouto** [comment]
Here is the logic
https://github.com/rilifon/liquidum/blob/main/project/game/random_menu/RandomHub.gd#L160-L163
The first array are the strategies it *may* use, the second is the strategies it must use at least one of them.

The current difference is:
- Expert not always uses boats and diags.
- Expert *may* use AdvancedRow and AdvancedCol while hard never does
- Using boat or allwater rules is no longer enough for it to be considered Expert (but Together/Separate rules still are)
- It's 5x5 instead of 5x4, slightly bigger

Possible things to make it harder:
- Move the together/separate from the second array to the first.
- Make it bigger
- Make visibility be a little more hidden (right now it works exactly the same as hard)
- Use aquariums, though we don't have a generator or solver for that

**Comment by yancouto** [comment]
I've separated Together/Separate rules into a "Basic" and "Advanced" version, so we can split the difficulties better.

**Comment by yancouto** [comment]
Expert also now has usually less visible hints, and may have aquarium hints.
