### ISSUE TITLE
Check ad volume

### ISSUE THREAD

**Issue by yancouto** [MarvellousSoft/liquidum#278]
It's louder than the game. Hard to test because we don't see real ads with sound.

**Comment by yancouto** [comment]
The official SDK has this function: https://developers.google.com/android/reference/com/google/android/gms/ads/MobileAds#setAppVolume(float)

But the plugin on Godot does not. We should maybe add it, if it's not too hard. Or also maybe just make the game louder so people decrease volume on their mobile. We should also maybe remove the "Master volume" option, since that's not super common in mobile.

**Comment by rilifon** [comment]
So our solution was:
- We now hide the master volume in the mobile version settings
- We hard set the master volume to a fixed value in mobile
This way the player will use the built-in mobile buttons to set the audio, and hopefully the overall audio will be ok even when ads roll, since atm we don't have control over that
